FROM ubuntu:18.04

RUN apt update && \
  apt install -y curl

###############################
## INSTALL node / npm
###############################

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt install -y nodejs

###############################
## INSTALL / RUN examples client
###############################

ENV CLIENT_DIR /buerli
RUN mkdir -p $CLIENT_DIR
WORKDIR $CLIENT_DIR

COPY ./.npmrc ./
COPY ./package.json ./
COPY ./patches ./patches
RUN npm i

COPY ./ $CLIENT_DIR

CMD npm run start
