FROM ubuntu:18.04

RUN apt-get update && \
  apt-get install -y curl

###############################
## INSTALL node / npm
###############################

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt-get install -y nodejs

###############################
## INSTALL / RUN examples client
###############################

ENV CLIENT_DIR /buerli
RUN mkdir -p $CLIENT_DIR
WORKDIR $CLIENT_DIR

COPY ./package.json ./
RUN npm i

COPY ./ $CLIENT_DIR

CMD npm run start
