FROM ubuntu:18.04

RUN apt update && \
  apt install -y curl

###############################
## INSTALL node / npm / yarn
###############################

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt install -y nodejs
RUN npm i -g yarn

###############################
## INSTALL / RUN examples client
###############################

ENV CLIENT_DIR /buerli
RUN mkdir -p $CLIENT_DIR

COPY ./ $CLIENT_DIR

WORKDIR $CLIENT_DIR
RUN yarn
CMD yarn start
