version: '3.5'

services:
  buerli-examples-client:
    build:
      context: ./client
      dockerfile: dockerfile
    image: buerli/examples-client
    container_name: buerli-examples-client
    tty: true
    stdin_open: true
    networks:
      - examples-network
    ports:
      - 8082:8082 # Webpack Server
    restart: unless-stopped

  buerli-examples-server:
    build:
      context: ./server
      dockerfile: dockerfile
    image: buerli/examples-server
    container_name: buerli-examples-server
    tty: true
    stdin_open: true
    networks:
      - examples-network
    ports:
      - 9091:9091 # ClassCAD Server
    restart: unless-stopped

networks:
  examples-network:
    name: buerli-network
