FROM ubuntu:18.04

RUN apt update

# Install node and npm
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt install -y nodejs

# Install linux dependencies
RUN apt install -y libicu60
RUN apt install -y libglu1-mesa-dev
RUN apt install -y ocl-icd-opencl-dev
RUN apt install -y locales
RUN locale-gen en_US.UTF-8

# Install ClassCAD
ENV SERVER_DIR /buerli
RUN mkdir -p $SERVER_DIR
WORKDIR $SERVER_DIR


#########################
COPY ./.npmrc $SERVER_DIR
COPY ./.yarnrc $SERVER_DIR
#########################


RUN npm init -y
RUN npm i @awvinf/classcad-linux-x64
RUN chmod +x ./node_modules/@awvinf/classcad-linux-x64/ClassCADInstance

# Copy runtimes to libs
RUN cp ./node_modules/@awvinf/classcad-linux-x64/libboost_thread.so.1.65.1 /lib/x86_64-linux-gnu

# Copy the .ccapp downloaded from buerli.io.
# Replace <PATH-TO-CCAPP-FILE> with the path pointing to the downloaded .ccapp file.
COPY ./EnterpriseBaseModeling.ccapp modeling.ccapp

# Start the server
EXPOSE 8182/tcp
CMD npx classcad --ip 0.0.0.0 --port 8182 --instances 5 --ccappfile modeling.ccapp
