FROM ubuntu:18.04

# Use this for M1 Macs
# FROM --platform=linux/amd64 dokken/ubuntu-18.04

# Install linux dependencies
RUN apt-get update && apt-get install -y \
    libglu1-mesa-dev \
    ocl-icd-opencl-dev \
    libarchive-dev \
    libgomp1 \
    locales

# Language settings
ENV LANG C
ENV LANGUAGE C
ENV LC_ALL C

# Install node and npm
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -y nodejs

# Install ClassCAD
ENV SERVER_DIR /classcad
RUN mkdir -p $SERVER_DIR
WORKDIR $SERVER_DIR

RUN npm init -y
RUN npm i @classcad/linux-x64@0.0.6
RUN chmod +x /classcad/node_modules/@classcad/linux-x64/ClassCADInstance

# Add classcad package dir to LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH="/classcad/node_modules/@classcad/linux-x64:$LD_LIBRARY_PATH"

# Copy the .ccapp downloaded from buerli.io.
COPY ./FreeBaseModeling.ccapp modeling.ccapp

# Start the server
EXPOSE 9091/tcp
CMD npx classcad --ip 0.0.0.0 --port 9091 --instances 5 --ccappfile modeling.ccapp

# Start the docker container as follows:
#
# docker run -p 9091:9091 <ID of the image>
#
# Or use the docker-compose configuration (see root of repository) to start server and client.
