FROM ubuntu:18.04

# Install linux dependencies
RUN apt-get update && apt-get install -y \
    libicu60 \
    libglu1-mesa-dev \
    ocl-icd-opencl-dev \
    locales

# Language settings
ENV LANG C
ENV LANGUAGE C
ENV LC_ALL C

# Install node and npm
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt-get install -y nodejs

# Install ClassCAD
ENV SERVER_DIR /buerli
RUN mkdir -p $SERVER_DIR
WORKDIR $SERVER_DIR

RUN npm init -y
RUN npm i @awvinf/classcad-linux-x64@0.0.0-beta.7
RUN chmod +x ./node_modules/@awvinf/classcad-linux-x64/ClassCADInstance

# Copy runtimes to libs
RUN cp ./node_modules/@awvinf/classcad-linux-x64/libboost_thread.so.1.65.1 /lib/x86_64-linux-gnu

# Copy the .ccapp downloaded from buerli.io.
COPY ./FreeBaseModeling.ccapp modeling.ccapp

# Start the server
EXPOSE 8081/tcp
CMD npx classcad --ip 0.0.0.0 --port 8081 --instances 5 --ccappfile modeling.ccapp

# Start the docker container as follows:
#
# docker run -p 8081:8081 <ID of the image>
#
# Or use the docker-compose configuration (see root of repository) to start server and client.
